In [ ]:
%pip install nltk
%pip install numpy
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.2 MB 653.6 kB/s eta 0:00:15
   ---------------------------------------- 0.1/9.2 MB 1.3 MB/s eta 0:00:08
   - -------------------------------------- 0.2/9.2 MB 1.8 MB/s eta 0:00:05
   - -------------------------------------- 0.4/9.2 MB 2.1 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/9.2 MB 2.4 MB/s eta 0:00:04
   --- ------------------------------------ 0.9/9.2 MB 3.4 MB/s eta 0:00:03
   ---- ----------------------------------- 0.9/9.2 MB 2.8 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/9.2 MB 4.5 MB/s eta 0:00:02
   ------- -------------------------------- 1.6/9.2 MB 4.5 MB/s eta 0:00:02
   ---------- ----------------------------- 2.5/9.2 MB 5.7 MB/s eta 0:00:02
   ---------- -----------------------

In [ ]:
from nltk import WhitespaceTokenizer
from nltk.corpus import stopwords
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import spacy

In [ ]:
nlp = spacy.load('ru_core_news_sm')

In [ ]:
Mashenka = open("c:\\Users\\maria\\Downloads\\Nabokov_Mashenka.txt").read() # Машенька (1926)
Camera = open("c:\\Users\\maria\\Downloads\\Camera_Obscura.txt").read() # Камера обскура (1932)
Despair = open("c:\\Users\\maria\\Downloads\\Nabokov_-_Otchayanie.txt").read() # Отчаяние (1934)
Gift = open("c:\\Users\\maria\\Downloads\\Dar.txt").read() # Дар (1938)
Lolita = open("c:\\Users\\maria\\Downloads\\Lolita1.txt").read() # Лолита (1955)
Transparent = open("c:\\Users\\maria\\Downloads\\Prozrachnye_predmety.txt").read() # Прозрачные предметы (1972)
books = [Mashenka, Camera, Despair, Gift, Lolita, Transparent]

In [43]:
def preprocessing(text):
    words = WhitespaceTokenizer().tokenize(text)
    stop = stopwords.words('russian')
    filtered_words = [word for word in words if word.lower() not in stop]
    doc = nlp(' '.join(filtered_words))
    words_lemma = [token.lemma_ for token in doc if not token.is_punct and not token.is_stop]
    return words_lemma

In [44]:
def calculate_cosine_similarity(books):
    preprocessed_books = [preprocessing(book) for book in books]
    preprocessed_books_to_strings = [' '.join(book) for book in preprocessed_books]
    vectors = CountVectorizer()
    book_vectors = vectors.fit_transform(preprocessed_books_to_strings)
    similarity = cosine_similarity(book_vectors)
    return similarity

In [45]:
similarity_matrix = calculate_cosine_similarity(books)
print(similarity_matrix)

[[1.         0.47905606 0.4319147  0.52034337 0.55168111 0.43015325]
 [0.47905606 1.         0.45089082 0.51961437 0.58332526 0.44917287]
 [0.4319147  0.45089082 1.         0.50472642 0.54457718 0.42720581]
 [0.52034337 0.51961437 0.50472642 1.         0.69576613 0.5700097 ]
 [0.55168111 0.58332526 0.54457718 0.69576613 1.         0.64537399]
 [0.43015325 0.44917287 0.42720581 0.5700097  0.64537399 1.        ]]
